package com.excelutility.util;

public enum ResourceKeys {
    HEADING_LABEL,
    FILE_PATH_LABEL,
    ROW_COUNT_LABEL,
    START_VALUE_LABEL,
    CONSTANT_STRING_LENGTH_LABEL,
    STEP_VALUE_LABEL,
    SHEET_NAME_LABEL,

    FILE_PATH_DESC,
    ROW_COUNT_DESC,
    START_VALUE_DESC,
    STEP_VALUE_DESC,
    CONSTANT_STRING_LENGTH_DESC,
    SHEET_NAME_DESC,

    GENERATE_RECORDS_LABEL,

    FILE_PATH_DEFAULT,
    ROW_COUNT_DEFAULT,
    START_VALUE_DEFAULT,
    STEP_VALUE_DEFAULT,
    CONSTANT_STRING_LENGTH_DEFAULT,
    SHEET_NAME_DEFAULT,

    INVALID_ROWS_VALUE,
    INVALID_STAT_VALUE,
    INVALID_STEP_VALUE,
    INVALID_CONSTANT_STRING_LENGTH,
    WRITING_STARTED_MESSAGE,
    WRITING_DONE_MESSAGE,
    ERROR_LOG_LABEL,
    LOGS_LABEL,
    UNABLE_TO_CREATE_DIRECTORY_MESSAGE
}
